# =========================================================
# BASE URLS
base.url=https://practicesoftwaretesting.com
base.url.api=https://gorest.co.in

# =========================================================
# AUTH
auth.token=64a4cad05f87de40f6c75e39a0025c53ad298fea597a0deb47490c5ff02d01bd

# UI ENGINE
# options: selenium, playwright
# =========================================================
ui.engine=playwright
ui.headless=false

# UI WINDOW
# ui.window.mode options: fullscreen
# ui.window.size format: WIDTHxHEIGHT
# =========================================================
ui.window.mode=fullscreen
ui.window.size=
ui.page.zoom.percent=60

# UI SCREENSHOTS
# =========================================================
ui.screenshots.enabled=true
ui.screenshots.on.failure.only=false
ui.screenshots.capture.final.state=true

# WAITS & RETRIES
# =========================================================
ui.wait.timeout.seconds=20
api.wait.timeout.seconds=10

api.rate.limit.max.retries=2
api.rate.limit.retry.default.delay.seconds=5
api.rate.limit.retry.max.delay.seconds=65

# REPORTING
# reporting.engine options: allure, extent
# =========================================================
reporting.engine=extent
reports.dir=target/reports

reports.timestamp.enabled=true
reports.timestamp.format=yyyy-MM-dd_HH-mm-ss

console.details.enabled=true
