package com.endava.ai.ui.tests;

import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserContext;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import com.microsoft.playwright.options.AriaRole;
import com.microsoft.playwright.options.MouseButton;

import java.util.regex.Pattern;

import static com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat;

public class Example {
    public static void main(String[] args) {
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));
            BrowserContext context = browser.newContext();
            Page page = context.newPage();
            page.navigate("https://practicesoftwaretesting.com/auth/register");
            page.locator("[data-test=\"first-name\"]").click();
            page.locator("[data-test=\"first-name\"]").click();
            page.locator("[data-test=\"first-name\"]").click();
            page.locator("[data-test=\"first-name\"]").fill("NAme");
            page.locator("[data-test=\"first-name\"]").press("Tab");
            page.locator("[data-test=\"last-name\"]").fill("LastName");
            page.locator("[data-test=\"dob\"]").click();
            page.locator("[data-test=\"dob\"]").fill("1991-01-01");
            page.locator("[data-test=\"country\"]").selectOption("AT");
            page.locator("[data-test=\"country\"]").selectOption("FK");
            page.locator("[data-test=\"postal_code\"]").click();
            page.locator("[data-test=\"postal_code\"]").fill("fdsffdd");
            page.locator("[data-test=\"postal_code\"]").dblclick();
            page.locator("[data-test=\"postal_code\"]").fill("5555");
            page.locator("[data-test=\"house_number\"]").click();
            page.locator("[data-test=\"house_number\"]").fill("5");
            page.locator("div").filter(new Locator.FilterOptions().setHasText("Customer registrationFirst")).nth(2).click();
            page.locator("[data-test=\"phone\"]").click();
            page.locator("[data-test=\"phone\"]").fill("778778877878");
            page.locator("[data-test=\"email\"]").click();
            page.locator("[data-test=\"email\"]").fill("a@b.com");
            page.locator("[data-test=\"password\"]").click();
            page.locator("[data-test=\"password\"]").click();
            page.locator("[data-test=\"password\"]").fill("Test1234Test");
            page.locator("[data-test=\"register-form\"]").getByRole(AriaRole.BUTTON).filter(new Locator.FilterOptions().setHasText(Pattern.compile("^$"))).click();
            page.locator("[data-test=\"password\"]").click();
            page.locator("[data-test=\"password\"]").press("ControlOrMeta+a");
            page.locator("[data-test=\"password\"]").press("ControlOrMeta+c");
            page.locator("[data-test=\"password\"]").press("ControlOrMeta+c");
            page.locator("[data-test=\"email\"]").click();
            page.locator("[data-test=\"email\"]").press("ControlOrMeta+a");
            page.locator("[data-test=\"email\"]").press("ControlOrMeta+c");
            page.getByText("Customer registrationFirst").click();
            page.getByText("Your password must: Be at").click();
            page.getByText("Your password must: Be at").click(new Locator.ClickOptions().setButton(MouseButton.RIGHT));
            page.getByText("Be at least 8 characters long").click();
            page.getByText("Contain both uppercase and").click();
            page.getByText("Include at least one number").click();
            page.getByText("Have at least one special").click();
            page.locator("[data-test=\"register-submit\"]").click();
            page.getByText("Password can not include").click();
            page.locator("[data-test=\"password\"]").click();
            page.locator("[data-test=\"register-submit\"]").click();
            page.locator("[data-test=\"register-submit\"]").click();
            page.locator("[data-test=\"password\"]").click();
            page.locator("[data-test=\"password\"]").click();
            page.locator("[data-test=\"password\"]").fill("Test1234Test!");
            page.locator("[data-test=\"password\"]").press("ControlOrMeta+a");
            page.locator("[data-test=\"password\"]").press("ControlOrMeta+c");
            page.locator("[data-test=\"password\"]").press("ControlOrMeta+c");
            page.locator("div").filter(new Locator.FilterOptions().setHasText("Customer registrationFirst")).nth(2).click();
            page.locator("[data-test=\"register-submit\"]").click();
            page.getByText("The given password has").click();
            page.locator("[data-test=\"password\"]").click();
            page.locator("[data-test=\"password\"]").fill("Test1234Test!Ana");
            page.locator("[data-test=\"password\"]").press("ControlOrMeta+a");
            page.locator("[data-test=\"password\"]").press("ControlOrMeta+c");
            page.locator("[data-test=\"register-submit\"]").click();
            page.getByText("Login Sign in with Google or").click();
            page.getByText("Not yet an account? Register").click();
            page.locator("[data-test=\"email\"]").click();
            page.locator("[data-test=\"email\"]").fill("a@b.com");
            page.locator("[data-test=\"password\"]").click();
            page.locator("[data-test=\"password\"]").fill("Test1234Test!Ana");
            page.locator("[data-test=\"login-submit\"]").click();
            page.getByText("This is a DEMO application (").click();
            page.locator("[data-test=\"nav-favorites\"]").click();
            page.navigate("https://practicesoftwaretesting.com/account");
            page.locator("[data-test=\"nav-profile\"]").click();
            page.getByText("First name").click();
            page.locator("[data-test=\"first-name\"]").click(new Locator.ClickOptions().setButton(MouseButton.RIGHT));
            page.getByText("Email address").click();
            page.getByText("Phone").click();
            page.getByText("Street").click();
            page.getByText("City").click();
            page.getByText("State").click();
            page.getByText("Country").click();
            page.locator("[data-test=\"street\"]").click();
            page.locator("[data-test=\"postal_code\"]").click();
            page.locator("[data-test=\"city\"]").click();
            page.locator("[data-test=\"current-password\"]").click();
            page.locator("[data-test=\"current-password\"]").fill("Test1234Test!Ana");
            page.locator("[data-test=\"new-password\"]").click();
            page.locator("[data-test=\"new-password\"]").fill("MiauMiau!123");
            page.getByRole(AriaRole.BUTTON).filter(new Locator.FilterOptions().setHasText(Pattern.compile("^$"))).first().click();
            page.locator("[data-test=\"new-password\"]").click();
            page.locator("[data-test=\"new-password\"]").press("ControlOrMeta+a");
            page.locator("[data-test=\"new-password\"]").press("ControlOrMeta+c");
            page.locator("[data-test=\"new-password-confirm\"]").dblclick();
            page.locator("[data-test=\"new-password-confirm\"]").fill("MiauMiau!123");
            page.locator("[data-test=\"change-password-submit\"]").click();
            page.getByText("Your password is successfully").click();
            page.locator("[data-test=\"password\"]").dblclick();
            page.locator("[data-test=\"password\"]").fill("MiauMiau!123");
            page.locator("div").filter(new Locator.FilterOptions().setHasText("Login Sign in with Google or")).nth(2).click();
            page.locator("[data-test=\"email\"]").click();
            page.locator("[data-test=\"email\"]").fill("a@b.com");
            page.locator("[data-test=\"login-submit\"]").click();
            page.getByText("This is a DEMO application (").click();
            assertThat(page.locator("[data-test=\"first-name\"]")).hasValue("NAme");
            assertThat(page.locator("app-profile")).matchesAriaSnapshot("- button \"Update Profile\"");
            page.getByText("View the Documentation for this application. Practice Black Box Testing & Bug").click();
            assertThat(page.locator("[data-test=\"last-name\"]")).hasValue("LastName");
        }
    }
}
